
name: Build .NET

trigger:
- main


variables:
- name: 'SolutionName'
  value: 'MediaArchive'
- name: 'Build.Configuration'
  value: 'Release'


stages:
- stage: Build

  jobs:
  - job: Backend
    pool: 
      vmImage: ubuntu-latest

    steps:
    - checkout: self
  
    - task: NuGetAuthenticate@1
  
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 6.0

    - task: UseDotNet@2
      displayName: 'Install .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Build Target ($(SolutionName))'
      inputs:
        command: build
        projects: '$(SolutionName)/$(SolutionName).sln'
        arguments: '--configuration $(Build.Configuration)'

    - task: DotNetCoreCLI@2
      displayName: 'Run All tests'
      inputs:
        command: 'test'
        projects: '$(SolutionName)/**/*[Tt]est*/*.csproj'
        publishTestResults: false
        arguments: '--configuration $(BuildConfiguration)'

    - script: |
        docker --version
        docker image ls
        docker container ls
