// <auto-generated />
using Common.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Database.Model.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EpisodeSign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episode");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Description",
                            EpisodeSign = "S1E1",
                            SeasonId = 1,
                            Title = "MyEpisode",
                            VideoPath = "default/videos/LifeOfBrian.mp4"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Description",
                            EpisodeSign = "S1E2",
                            SeasonId = 1,
                            Title = "MyEpisode2",
                            VideoPath = "default/videos/LifeOfBrian.mp4"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The other description",
                            EpisodeSign = "S2E1",
                            SeasonId = 2,
                            Title = "New Episode",
                            VideoPath = "default/videos/LifeOfBrian.mp4"
                        });
                });

            modelBuilder.Entity("Common.Database.Model.Header", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ThumbNailPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Header");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ThumbNailPath = "default/images/closeup-open-textbook.jpg",
                            Title = "Show Title"
                        });
                });

            modelBuilder.Entity("Common.Database.Model.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Picture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EpisodeId = 1,
                            ImagePath = "default/images/closeup-open-textbook.jpg"
                        },
                        new
                        {
                            Id = 2,
                            EpisodeId = 1,
                            ImagePath = "default/images/open-page.jpg"
                        },
                        new
                        {
                            Id = 3,
                            EpisodeId = 1,
                            ImagePath = "default/images/open-page-2.jpg"
                        },
                        new
                        {
                            Id = 4,
                            EpisodeId = 2,
                            ImagePath = "default/images/closeup-open-textbook.jpg"
                        },
                        new
                        {
                            Id = 5,
                            EpisodeId = 2,
                            ImagePath = "default/images/open-page.jpg"
                        },
                        new
                        {
                            Id = 6,
                            EpisodeId = 3,
                            ImagePath = "default/images/closeup-open-textbook.jpg"
                        },
                        new
                        {
                            Id = 7,
                            EpisodeId = 3,
                            ImagePath = "default/images/open-page.jpg"
                        },
                        new
                        {
                            Id = 8,
                            EpisodeId = 3,
                            ImagePath = "default/images/open-page-2.jpg"
                        });
                });

            modelBuilder.Entity("Common.Database.Model.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeaderId");

                    b.ToTable("Season");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeaderId = 1,
                            Title = "Season I"
                        },
                        new
                        {
                            Id = 2,
                            HeaderId = 1,
                            Title = "Season II"
                        });
                });

            modelBuilder.Entity("Common.Database.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int>("PictureId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("EpisodeTag", b =>
                {
                    b.Property<int>("EpisodesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("EpisodesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("EpisodeTags", (string)null);
                });

            modelBuilder.Entity("PictureTag", b =>
                {
                    b.Property<int>("PicturesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("PicturesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PictureTags", (string)null);
                });

            modelBuilder.Entity("Common.Database.Model.Episode", b =>
                {
                    b.HasOne("Common.Database.Model.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Common.Database.Model.Picture", b =>
                {
                    b.HasOne("Common.Database.Model.Episode", "Episode")
                        .WithMany("Pictures")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Common.Database.Model.Season", b =>
                {
                    b.HasOne("Common.Database.Model.Header", "Header")
                        .WithMany("Seasons")
                        .HasForeignKey("HeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("EpisodeTag", b =>
                {
                    b.HasOne("Common.Database.Model.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PictureTag", b =>
                {
                    b.HasOne("Common.Database.Model.Picture", null)
                        .WithMany()
                        .HasForeignKey("PicturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Database.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Database.Model.Episode", b =>
                {
                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("Common.Database.Model.Header", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Common.Database.Model.Season", b =>
                {
                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
