name: Build and Test .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-dotnet:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore MediaArchive.sln

      - name: Build
        run: dotnet build MediaArchive.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test MediaArchive.sln --configuration Release --no-build --verbosity normal

      - name: Publish Artifacts for Release (cache)
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          dotnet publish MediaController/MediaController.csproj -c Release -o ./out/mediacontroller

      - name: Create archive
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          mkdir -p ./out/archive
          tar -czvf ./out/archive/mediacontroller.tar.gz -C ./out/mediacontroller .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediacontroller
          path: ./out/archive/mediacontroller.tar.gz

  build-frontend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build frontend
        run: |
          cd media-archive-frontend
          rm -rf node_modules package-lock.json
          npm install
          npm run build

      # - name: Test frontend
      #   run: |
      #     cd media-archive-frontend
      #     npm run test --no-watch

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./media-archive-frontend/dist

  docker:
    runs-on: ubuntu-22.04
    needs: [build-dotnet, build-frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build dotnet image
        run: docker compose -f docker-compose-override.yaml build mediacontroller

      - name: Build frontend image
        run: docker compose -f docker-compose-override.yaml build frontend

      - name: Prepare image output directory
        run: mkdir -p ./out/images

      - name: Save dotnet image
        run: docker save mediacontroller:latest -o ./out/images/mediacontroller.tar

      - name: Save frontend image
        run: docker save frontend:latest -o ./out/images/frontend.tar

      - name: Upload docker images artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: ./out/images