name: Build and Test .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore MediaArchive.sln

      - name: Build
        run: dotnet build MediaArchive.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test MediaArchive.sln --configuration Release --no-build --verbosity normal

      - name: Publish Artifacts for Release (cache)
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          dotnet publish MediaController/MediaController.csproj -c Release -o ./out/mediacontroller

      - name: Create archive
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          mkdir -p ./out/archive
          tar -czvf ./out/archive/mediacontroller.tar.gz -C ./out/mediacontroller .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mediacontroller
          path: ./out/archive/mediacontroller.tar.gz
      